### ISSUE TITLE
Allow XML encodings other than us-ascii

### ISSUE THREAD

**Issue by gregoa** [ap/XML-Atom-SimpleFeed#2]
We have the following bug reported to the Debian package of
XML-Atom-SimpleFeed (https://bugs.debian.org/793069):

It doesn't seem to be a bug in the packaging, so you may want to take
a look. Thanks!

------8<-----------8<-----------8<-----------8<-----------8<-----

```
Package: libxml-atom-simplefeed-perl
Version: 0.86-2
Severity: wishlist
Tags: upstream

Hi!

The output has the encoding hardcoded to us-ascii. It would be nice to
either change that to utf-8 or at least make it configurable.

Thanks,
Guillem


```

------8<-----------8<-----------8<-----------8<-----------8<-----

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by ap** [comment]
This is a very, very longstanding issue, originally filed as a CPAN RT way back in 2006:
- [#19722: Can't make it to work with international charsets](https://rt.cpan.org/Ticket/Display.html?id=19722)

Since then, I learned how Unicode in Perl actually works, then floundered for years, then made an abortive attempt to write an XML emitter module that doesn’t suck ([XML::Builder](https://metacpan.org/pod/XML::Builder)). But I think I know how to tackle the problem now – as of just a few days ago, coincidentally.

**Comment by gregoa** [comment]
On Mon, 21 Sep 2015 12:11:08 -0700, Aristotle Pagaltzis wrote:

> Since then, I learned how Unicode in Perl actually works, then
> floundered for years, then made an abortive attempt to write an XML
> emitter module that doesn’t suck
> ([XML::Builder](https://metacpan.org/pod/XML::Builder)). But I
> think I know how to tackle the problem now – as of just a few days
> ago, coincidentally.

That's good news and a nice coincidence :)

Thanks in advance,
gregor

## 

 .''`.  Homepage: http://info.comodo.priv.at/ - OpenPGP key 0xBB3A68018649AA06
 : :' : Debian GNU/Linux user, admin, and developer -  https://www.debian.org/
`. `'  Member of VIBE!AT & SPI, fellow of the Free Software Foundation Europe
`\-   NP: Tom Waits: Swordfish Trombone

**Comment by ap** [comment]
Actually I ended up doing it in a completely different way from what I was thinking of; I ended up preferring to make minimum changes. (The other way that I was thinking of will first go into XML::Builder where it will form the basis for a rewrite of this module under a different name. That’s the plan anyway.)

Anyhow, 0.900 is now winding its way to the CPAN. \o/

**Comment by gregoa** [comment]
On Tue, 22 Sep 2015 05:39:02 -0700, Aristotle Pagaltzis wrote:

> Anyhow, 0.900 is now winding its way to the CPAN. \o/

Great, thanks.

Uploaded to Debian/unstable.

Cheers,
gregor

## 

 .''`.  Homepage: http://info.comodo.priv.at/ - OpenPGP key 0xBB3A68018649AA06
 : :' : Debian GNU/Linux user, admin, and developer -  https://www.debian.org/
`. `'  Member of VIBE!AT & SPI, fellow of the Free Software Foundation Europe
`\-   NP: Pink Floyd: Another Brick In The Wall (part 2)
